trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build'

  - script: |
      npm test
    displayName: 'Run Tests'
